#!/bin/zsh

# Colores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

clear
echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          📚 GUÍA DE USO - GENERADOR DE MÓDULOS            ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

echo -e "${YELLOW}═══ ARQUITECTURA DEL PROYECTO ═══${NC}"
echo ""
echo -e "${BLUE}Domain Layer${NC} (Reglas de negocio)"
echo "  └── domain/"
echo "      ├── models/           → Entidades del dominio"
echo "      ├── repositories/     → Interfaces de repositorios"
echo "      └── mappers/          → Transformadores DTO ↔ Model"
echo ""
echo -e "${BLUE}Infrastructure Layer${NC} (Implementación técnica)"
echo "  └── infrastructure/"
echo "      ├── dto/              → Data Transfer Objects"
echo "      ├── repositories/     → Implementación de repositorios"
echo "      └── services/         → Servicios HTTP"
echo ""
echo -e "${BLUE}Application Layer${NC} (Casos de uso)"
echo "  └── application/"
echo "      └── use-cases/        → Lógica de aplicación"
echo ""

echo -e "${YELLOW}═══ FLUJO DE CREACIÓN DE MÓDULOS ═══${NC}"
echo ""
echo -e "${GREEN}Opción 1: Módulo Completo (Recomendado)${NC}"
echo "  1. Ejecutar: ${CYAN}./dev.sh${NC}"
echo "  2. Seleccionar opción ${GREEN}4${NC} (Crear Módulo Completo)"
echo "  3. Seguir el asistente paso a paso"
echo "  4. Se crearán automáticamente:"
echo "     → Models (Request/Response)"
echo "     → DTOs"
echo "     → Mappers"
echo "     → Service"
echo "     → Repository (Interface + Implementation)"
echo ""
echo -e "${GREEN}Opción 2: Creación Individual${NC}"
echo "  Orden recomendado:"
echo "  ${CYAN}1.${NC} Model     → Define las entidades"
echo "  ${CYAN}2.${NC} Service   → Implementa la lógica HTTP"
echo "  ${CYAN}3.${NC} Repository → Conecta con el dominio"
echo ""

echo -e "${YELLOW}═══ COMANDOS DISPONIBLES ═══${NC}"
echo ""
echo -e "${CYAN}./dev.sh${NC}"
echo "  Menú principal interactivo"
echo ""
echo -e "${CYAN}./commands/model.sh${NC}"
echo "  Crea: Models + DTOs + Mappers"
echo "  Opciones: Request/Response o Model simple"
echo ""
echo -e "${CYAN}./commands/service.sh${NC}"
echo "  Crea: Service con integración automática de Mapper"
echo ""
echo -e "${CYAN}./commands/repository.sh${NC}"
echo "  Crea: Repository (Domain + Implementation)"
echo "  Auto-detecta: Models y Services relacionados"
echo "  Auto-actualiza: app.config.ts"
echo ""
echo -e "${CYAN}./commands/usecase.sh${NC}"
echo "  Crea: Use Case en Application Layer"
echo "  Auto-detecta: Repositories disponibles"
echo ""
echo -e "${CYAN}./commands/validate.sh${NC}"
echo "  Valida la estructura del proyecto"
echo "  Muestra estadísticas de módulos"
echo ""
echo -e "${CYAN}./commands/inspect.sh${NC}"
echo "  Inspecciona un módulo específico"
echo "  Muestra todos los componentes y exports"
echo ""

echo -e "${YELLOW}═══ EJEMPLOS DE USO ═══${NC}"
echo ""
echo -e "${MAGENTA}Ejemplo 1: Crear módulo de autenticación${NC}"
echo "  $ ./dev.sh"
echo "  Opción: 4 (Módulo Completo)"
echo "  Directorio: ${GREEN}auth${NC}"
echo "  Archivo: ${GREEN}auth${NC}"
echo "  Request: ${GREEN}Sí${NC}"
echo "  Response: ${GREEN}Sí${NC}"
echo "  DTO: ${GREEN}Sí${NC}"
echo "  Mapper: ${GREEN}Sí${NC}"
echo ""
echo "  ${CYAN}Resultado:${NC}"
echo "  ✓ src/app/domain/models/auth/request/auth-request.model.ts"
echo "  ✓ src/app/domain/models/auth/response/auth-response.model.ts"
echo "  ✓ src/app/infrastructure/dto/request/auth-request.dto.ts"
echo "  ✓ src/app/infrastructure/dto/response/auth-response.dto.ts"
echo "  ✓ src/app/domain/mappers/auth/auth.mapper.ts"
echo "  ✓ src/app/infrastructure/services/auth/auth.service.ts"
echo "  ✓ src/app/domain/repositories/auth/auth.repository.ts"
echo "  ✓ src/app/infrastructure/repositories/auth/auth.implementation.repository.ts"
echo ""

echo -e "${MAGENTA}Ejemplo 2: Crear un use case${NC}"
echo "  $ ./dev.sh"
echo "  Opción: 5 (Crear Use Case)"
echo "  Directorio: ${GREEN}auth${NC}"
echo "  Caso de uso: ${GREEN}login${NC}"
echo ""
echo "  ${CYAN}Resultado:${NC}"
echo "  ✓ src/app/application/use-cases/auth/login.use-case.ts"
echo "  ✓ Auto-detecta y conecta con AuthRepository"
echo ""

echo -e "${YELLOW}═══ CONVENCIONES DE NOMBRES ═══${NC}"
echo ""
echo "Directorio:  ${GREEN}kebab-case${NC}  (ej: auth, user-profile)"
echo "Archivo:     ${GREEN}kebab-case${NC}  (ej: auth, user-profile)"
echo "Clase Model: ${GREEN}PascalCase${NC} + Model  (ej: AuthModel)"
echo "Clase DTO:   ${GREEN}PascalCase${NC} + Dto    (ej: AuthDto)"
echo "Clase Service: ${GREEN}PascalCase${NC} + Service (ej: AuthService)"
echo "Clase Repository: ${GREEN}PascalCase${NC} + Repository (ej: AuthRepository)"
echo ""

echo -e "${YELLOW}═══ VENTAJAS DEL SISTEMA ═══${NC}"
echo ""
echo -e "${GREEN}✓${NC} Homologación del código"
echo -e "${GREEN}✓${NC} Auto-detección de dependencias"
echo -e "${GREEN}✓${NC} Actualización automática de configuración"
echo -e "${GREEN}✓${NC} Validación de estructura"
echo -e "${GREEN}✓${NC} Limpieza segura de módulos"
echo -e "${GREEN}✓${NC} Inspección detallada"
echo ""

echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
echo -e "  Para comenzar, ejecuta: ${GREEN}./dev.sh${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
echo ""

